name: Bedwars
main: Fludixx\Bedwars\Bedwars
author: Fludixx bug fix and improvement by DragKills
api: [4.0.0]
version: 4.0
description: Bedwars Plugin for Pocketmine

permissions:
  bw.admin:
    description: allow the player to edit/create arena
    default: op
  bw.start:
    description: allow player to start arena
    default: op
